# Generated by Django 3.2.16 on 2022-11-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_enable_realtime_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_case_sensitive_flags',
            field=models.BooleanField(default=False, help_text='Allow for case sensitive flags to be defined'),
        ),
    ]
